### ISSUE TITLE
Unable to remove ActivateWindow(shutdownmenu) from option tray

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse#633]
### Skin section

Widgets

### Current Behavior

showsActivateWindow(shutdownmenu) even though it has been removed in settings
<img width="1241" alt="Screen Shot 2024-03-24 at 11 51 21 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/0d083652-abf6-4a66-96f6-93983e6be15d">

### Expected Behavior

To not show anymore 

### Steps To Reproduce

1. option tray settings
2. delete/replace ActivateWindow(shutdownmenu)
3. still there

### Screenshots and Additional Info

I have removed/replaced ActivateWindow(shutdownmenu) with ActivateWindow(1170) because all the options work properly
<img width="1236" alt="Screen Shot 2024-03-24 at 11 52 00 AM" src="https://github.com/jurialmunkey/skin.arctic.fuse/assets/43726430/73d66c1a-008f-4a0c-a027-724de9c1b8d2">

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Blackysbd** [comment]
Also you can't open any of the menu options from the tray

**Comment by jurialmunkey** [comment]
The tray options button is forced, so you can delete it entirely from the config.

Originally it was going to be optional, which is why it carries over from the earlier config but then I realised I needed at least one button to be forced. It is no longer in the default but I'll never forcibly reset configs on people so if it has carried over you would need to delete it yourself.

The issue with the menu not working has nothing to do with `shutdownmenu` vs `1170`. These are identical -- shutdownmenu opens 1170 onload.

The issue is because the tray still being open blocks Kodi from switching windows, as Kodi considers all activated dialogs as modal.  The issue is fixed here by forcing it closed first before opening menu: https://github.com/jurialmunkey/skin.arctic.fuse/commit/aef0af2489a90a99954cafc57c0f5f61c5597a8d

**Comment by Liquidrag** [comment]
@jurialmunkey I like the tray option, problem is ActivateWindow(shutdownmenu) is deleted but still shows,
